### ISSUE TITLE
Document of webapp building has broken

### ISSUE THREAD

**Issue by johnroyer** [ocftw/open-star-ter-village#57]
document [WEBAPP.md](https://github.com/ocftw/open-star-ter-village/blob/main/WEBAPP.md) is broken.

From the document:
```
git clone git@github.com:ocftw/open-star-ter-village.git open-star-ter-village
cd open-star-ter-village/webapp
```

But there is no folder named `webapp`.

**Comment by ben196888** [comment]
That would be great if you could create a pull request to update our document as well!

**Comment by johnroyer** [comment]
It is works runnung `yarn` in project root folder. But there is error running `yarn build:webapp`:

```
Error: Cannot find module '/home/zero/devel/open-star-ter-village/node_modules/react-scripts/bin/react-scripts.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
```

----

I notice that there is `package.json` in project root. Then try this steps:

1. `cd /path/to/project/`
1. `npm install`
1. `yarn`
1. `yarn build:webapp`

but the same error occurs.

Is there any steps I missed?

**Comment by ben196888** [comment]
@johnroyer I guess the `npm install` command make it wrong. Both `npm` and `yarn` are the package management tools but they may conflict to each other. Please follow the following steps and give it a try.
1.a go to the project root folder. `cd <folder>/open-star-ter-village`
1.b remove the `node_modules` folder because you have installed dependencies via both `npm` and `yarn`. `rm -rf node_modules`
2. install dependencies `yarn`
3. run the build script `yarn build:webapp`

You can take step 1.a, 2 and 3 to build the webapp for the next time. You don't need to remove the `node_modules` folder.

**Comment by johnroyer** [comment]
yarn goes well after I delete `node_module`. Build steps in `WEBAPP.md` is no need to chagne.

I modified the root build path and send a pull request.
